### ISSUE TITLE
make rules for cshell and cppshell produce identical binaries

### ISSUE THREAD

**Issue by goddamnparticle** [goddamnparticle/eggshell#1]
when building the project with `make` it produce same binary for both `cshell` and `cppshell` rules.
- steps to reproduce:
`make`
- expected:
```
$ ./cshell
eggshell in c
$ ./cppshell
eggshell in c++
```
- actual:
```
$ ./cshell
eggshell in c
$ ./cppshell
eggshell in c
```

**Comment by muhammedenesbalci** [comment]
The reason for this issue is due to the file names. Since the file names for C and C++ are the same, confusion arises during the creation of object files (.o files). The problem is resolved when the file names are differentiated from each other.
